version: "3.8"
services:
  nginx:
    image: public.ecr.aws/z9q8j2y4/test-nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  api:
    image: public.ecr.aws/z9q8j2y4/test-api
    build:
        context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./api/dev.env
    ports:
      - "5000:5000"
  client:
    image: public.ecr.aws/z9q8j2y4/test-nginx
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
